name: Docker Image CI

on:
  push:
    branches: [ "general-devel" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Log in to container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and publish the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: tshock:latest
